# Generated by Django 5.1.1 on 2024-09-15 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Página')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('url', models.URLField(verbose_name='URL do Produto')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.paginaproduto')),
            ],
        ),
    ]
